"use client";

import { UserPlus } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/admin/ui/badge";
import { Button } from "@/components/admin/ui/button";
import { Input } from "@/components/admin/ui/input";
import { Label } from "@/components/admin/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/admin/ui/table";
type UserItem = { id: number; name: string; email: string; role: "ADMIN" | "EMPLOYEE"; preferredLocale: "FR" | "EN"; isActive: boolean; mustResetPassword: boolean; lastLoginAt: Date | null };

export function UserManager({ users, currentUserId, locale }: { users: UserItem[]; currentUserId: number; locale: "fr" | "en" }) {
  const router = useRouter(); const [busy, setBusy] = useState(false);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); setBusy(true); try { const response = await fetch("/api/admin/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: values.get("name"), email: values.get("email"), role: values.get("role"), preferredLocale: values.get("preferredLocale") }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Request failed"); toast.success(result.data.invitationSent ? (locale === "fr" ? "Utilisateur créé et invitation envoyée" : "User created and invitation sent") : (locale === "fr" ? "Utilisateur créé; e-mail non configuré" : "User created; email is not configured")); form.reset(); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Request failed"); } finally { setBusy(false); } }
  async function setActive(id: number, isActive: boolean) { setBusy(true); try { const response = await fetch(`/api/admin/users/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ isActive }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Request failed"); toast.success(locale === "fr" ? "Utilisateur mis à jour" : "User updated"); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Request failed"); } finally { setBusy(false); } }
  return <div className="space-y-6"><form onSubmit={create} className="grid gap-4 rounded-md border bg-card p-5 shadow-sm md:grid-cols-5"><div><Label htmlFor="user-name">{locale === "fr" ? "Nom" : "Name"}</Label><Input id="user-name" name="name" required /></div><div><Label htmlFor="user-email">Email</Label><Input id="user-email" name="email" type="email" required /></div><div><Label htmlFor="user-role">{locale === "fr" ? "Rôle" : "Role"}</Label><select id="user-role" name="role" className="h-9 w-full rounded-md border bg-background px-3 text-sm"><option value="EMPLOYEE">Employee</option><option value="ADMIN">Admin</option></select></div><div><Label htmlFor="user-locale">Language</Label><select id="user-locale" name="preferredLocale" className="h-9 w-full rounded-md border bg-background px-3 text-sm"><option value="FR">FR</option><option value="EN">EN</option></select></div><div className="flex items-end"><Button type="submit" disabled={busy}><UserPlus />{locale === "fr" ? "Inviter" : "Invite"}</Button></div></form><div className="overflow-hidden rounded-md border bg-card"><Table><TableHeader><TableRow><TableHead>{locale === "fr" ? "Utilisateur" : "User"}</TableHead><TableHead>{locale === "fr" ? "Rôle" : "Role"}</TableHead><TableHead>Status</TableHead><TableHead>{locale === "fr" ? "Mot de passe" : "Password"}</TableHead><TableHead>{locale === "fr" ? "Action" : "Action"}</TableHead></TableRow></TableHeader><TableBody>{users.map((user) => <TableRow key={user.id}><TableCell><strong>{user.name}</strong><div className="text-xs text-muted-foreground">{user.email}</div></TableCell><TableCell>{user.role}</TableCell><TableCell><Badge variant={user.isActive ? "success" : "secondary"}>{user.isActive ? (locale === "fr" ? "Actif" : "Active") : (locale === "fr" ? "Inactif" : "Inactive")}</Badge></TableCell><TableCell>{user.mustResetPassword ? (locale === "fr" ? "Initial requis" : "Initial reset required") : "✓"}</TableCell><TableCell><Button type="button" size="sm" variant="outline" disabled={busy || user.id === currentUserId} onClick={() => void setActive(user.id, !user.isActive)}>{user.isActive ? (locale === "fr" ? "Désactiver" : "Deactivate") : (locale === "fr" ? "Activer" : "Activate")}</Button></TableCell></TableRow>)}</TableBody></Table></div></div>;
}
