import type { NextRequest } from "next/server";
import { revalidatePath } from "next/cache";
import { NextResponse } from "next/server";
import { getCurrentAdminUser } from "@/server/auth/guard";
import { canManageUsers } from "@/server/auth/permissions";
import { prisma } from "@/server/db/prisma";
import { apiError, getClientIp, hasTrustedOrigin } from "@/server/http/api";
import { legalDocumentInputSchema } from "@/server/settings/validation";
export async function POST(request: NextRequest) { if (!hasTrustedOrigin(request)) return apiError("INVALID_ORIGIN", "Request origin is not allowed.", 403); const current = await getCurrentAdminUser(); if (!current) return apiError("UNAUTHENTICATED", "Authentication is required.", 401); if (!canManageUsers(current.role)) return apiError("FORBIDDEN", "Permission denied.", 403); const parsed = legalDocumentInputSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return apiError("VALIDATION_ERROR", "Please check the legal document.", 400, parsed.error.flatten().fieldErrors); const content = { type: "doc", content: parsed.data.body.split(/\n\s*\n/).map((paragraph) => ({ type: "paragraph", content: [{ type: "text", text: paragraph.trim() }] })) }; const data = await prisma.$transaction(async (tx) => { const value = await tx.legalDocument.upsert({ where: { type_locale: { type: parsed.data.type, locale: parsed.data.locale } }, create: { type: parsed.data.type, locale: parsed.data.locale, title: parsed.data.title, slug: parsed.data.slug, content, status: parsed.data.status, publishedAt: parsed.data.status === "PUBLISHED" ? new Date() : null }, update: { title: parsed.data.title, slug: parsed.data.slug, content, status: parsed.data.status, publishedAt: parsed.data.status === "PUBLISHED" ? new Date() : null, revision: { increment: 1 } } }); await tx.auditLog.create({ data: { userId: current.id, action: parsed.data.status === "PUBLISHED" ? "PUBLISH" : "UPDATE", entityType: "LegalDocument", entityId: value.id, ipAddress: getClientIp(request), userAgent: request.headers.get("user-agent") } }); return value; }); revalidatePath(`/${parsed.data.locale.toLowerCase()}/${parsed.data.type === "PRIVACY" ? "privacy-policy" : "terms"}`); return NextResponse.json({ data }); }
