"use client";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import { Button } from "@/components/admin/ui/button";
import { Input } from "@/components/admin/ui/input";
import { Label } from "@/components/admin/ui/label";
import { Textarea } from "@/components/admin/ui/textarea";
type Document = { id: number; type: "PRIVACY" | "TERMS"; locale: "FR" | "EN"; title: string; slug: string; status: string; content: unknown };
function text(content: unknown) { if (!content || typeof content !== "object") return ""; const nodes = (content as { content?: { content?: { text?: string }[] }[] }).content ?? []; return nodes.map((node) => node.content?.map((part) => part.text ?? "").join("") ?? "").join("\n\n"); }
export function LegalEditor({ documents, locale }: { documents: Document[]; locale: "fr" | "en" }) { const [busy, setBusy] = useState(false); async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setBusy(true); try { const response = await fetch("/api/admin/legal", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(data.entries())) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Save failed"); toast.success(locale === "fr" ? "Document enregistré" : "Document saved"); } catch (error) { toast.error(error instanceof Error ? error.message : "Save failed"); } finally { setBusy(false); } } return <section className="space-y-4"><h2 className="text-xl font-semibold">{locale === "fr" ? "Documents légaux" : "Legal documents"}</h2><div className="grid gap-5 lg:grid-cols-2">{(["PRIVACY", "TERMS"] as const).flatMap((type) => (["FR", "EN"] as const).map((language) => { const document = documents.find((item) => item.type === type && item.locale === language); return <form key={`${type}-${language}`} className="space-y-3 rounded-md border bg-card p-5" onSubmit={save}><input type="hidden" name="type" value={type} /><input type="hidden" name="locale" value={language} /><h3 className="font-semibold">{type} · {language}</h3><div><Label>Title</Label><Input name="title" defaultValue={document?.title ?? (type === "PRIVACY" ? (language === "FR" ? "Politique de confidentialité" : "Privacy policy") : (language === "FR" ? "Conditions générales" : "Terms & Conditions"))} required /></div><input type="hidden" name="slug" value={type === "PRIVACY" ? "privacy-policy" : "terms"} /><div><Label>Content</Label><Textarea name="body" rows={10} defaultValue={text(document?.content)} required /></div><select name="status" defaultValue={document?.status ?? "DRAFT"} className="h-9 w-full rounded-md border bg-background px-3 text-sm"><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select><Button disabled={busy}>{locale === "fr" ? "Enregistrer" : "Save"}</Button></form>; }))}</div></section>; }
